services:
  postgres:
    image: postgres:13.1
    container_name: nestjs-database-connection-postgres-db
    restart: always
    env_file:
      - ./.env
     
    volumes:
      - nestjs_postgres_db:/data/postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: nestjs-database-connection-adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  nestjs_postgres_db:
