version: '3.8'

services:
  mongodb:
    image: mongo:7.0.2
    container_name: nestjs-database-connection-mongo-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - nestjs_mongo_db_container:/data/db

volumes:
  nestjs_mongo_db_container:
